### PR TITLE
Add winget installation option to README

### PR DESCRIPTION
**Pull request by mariobrostech**
I recently submitted this app to the winget-pkgs repository, so it's now available to be installed from the winget package manager that's built into Windows. This PR would highlight this in the README so it's visible to more users. Please let me know if you release any updates and would like the winget package to be updated as well!

### CODE REVIEW

**Comment by tushev** [comment]
Hello @mariobrostech ,

Thank you for your effort! I was also considering publishing to **winget**, but you've got ahead of me :)

However, I would prefer different naming, such as `tushev.org`, and not Simon Tushev in **PackageIdentifier** etc, and some other changes. This is the manifest that I was preparing: https://gist.github.com/tushev/7dac512f201b9bf5a4a93edb10ab46a8
It's a singleton, but that format is deprecated now in favor of multi-file manifest. 

I would prefer to change the items marked with 🔵:
image


Would you like to submit those changes to the `winget-pkgs` repository, or should I do it myself?

<hr>

As for this pull request, I would love to add that info to **README**, once **PackageIdentifier** is changed in repository to `tushev.org.AJUpdateWatcher`.

Thanks!

**Comment by mariobrostech** [comment]
Hi, and thanks for the quick follow-up! My apologies for not reaching out and running this by you before I made my pull request in the `winget-pkgs` repository. At this point, I'm fine making the changes myself, but I'd prefer if you could instead so the changes match what you'd like and we don't have to go back-and-forth on technicalities. If you're comfortable with me making the changes myself, I will; just let me know.

**Comment by tushev** [comment]
@mariobrostech there's nothing to apologize for :)
In fact, if it weren't you, I would 'considering publishing' for another half of a year... :)

I've submitted the changes myself.
You were correct, there were a lot of technicalities, and it seems that I cannot change all I want without rebuilding the MSI itself, so I left some changes for the future. 

Nevertheless, thanks again for your contribution!

**Comment by mariobrostech** [comment]
Awesome, I'm happy I could help and that you got everything sorted out! Let me know if there's anything else I can do to help in the future :)

**Pull request merged**
